[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
datafusion = "42.0.0"
object_store = { version = "0.11.0", features = ["aws"] }
tokio = { version = "1.40.0", features = ["full"] }
url = "2.5.2"
